keys:
  - &thinkpad_x1 age1cfgl5syys3skkd73uayppvdp2688sch0tm3arl9cqvyw64esyymqtalfgs
creation_rules:
  - path_regex: '^\.secrets/.*\.(yaml|json|env|ini)$'
    key_groups:
      - age:
        - *thinkpad_x1